# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility).
Vagrant.configure(2) do |config|
  config.vm.box = "couchdb-ci-ubuntu-14.04"

  # How much memory do we need to test the setup? I have no clue.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # The base box also copies the Vagrant ssh key into root's authorized_keys
  # so we can ssh into the box via root. This way, there is no mention of the
  # user vagrant in the Ansible scripts.
  config.ssh.username = 'root'

  config.vm.define "couchdb-jenkins-master"

  # Workaround for "stdin: is not a tty error" -- make Vagrants ssh shell a
  # non-login one. See https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/site.yml"
    ansible.groups = {
      "jenkins-master" => ["jenkins-master"],
      "ubuntu" => ["ubuntu"]
    }
  end

  config.vm.network "forwarded_port", guest: 8080, host: 18080
end
