sudo: required

services:
  - docker

before_script:
  - docker --version

env:
  matrix:
    - PLATFORM=debian-jessie
    - PLATFORM=debian-stretch
    - PLATFORM=ubuntu-trusty
    - PLATFORM=ubuntu-xenial
    - PLATFORM=ubuntu-bionic
    - PLATFORM=centos-6
    - PLATFORM=centos-7

script:
  - ./build.sh js ${PLATFORM}
  - ./build.sh couch-pkg ${PLATFORM}

after_script:
  - ls -laR js
  - ls -laR couch
