dist: xenial

language: minimal

services:
  - docker

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

env:
  matrix:
    - PLATFORM=debian-stretch TARGET=base
    - PLATFORM=debian-stretch TARGET=platform
    - PLATFORM=debian-stretch TARGET=couch
    - PLATFORM=aarch64-debian-stretch TARGET=base
    # too slow!
    #- ERLANGVERSION=20.3.8.20 PLATFORM=aarch64-debian-stretch TARGET=platform
    #- ERLANGVERSION=20.3.8.20 PLATFORM=aarch64-debian-stretch TARGET=couch
    - PLATFORM=debian-buster TARGET=base
    - ERLANGVERSION=20.3.8.22-1 PLATFORM=debian-buster TARGET=platform
    - ERLANGVERSION=20.3.8.22-1 PLATFORM=debian-buster TARGET=couch
    - PLATFORM=ubuntu-xenial TARGET=base
    - PLATFORM=ubuntu-xenial TARGET=platform
    - PLATFORM=ubuntu-xenial TARGET=couch
    - PLATFORM=ubuntu-bionic TARGET=base
    - PLATFORM=ubuntu-bionic TARGET=platform
    - PLATFORM=ubuntu-bionic TARGET=couch
    - PLATFORM=centos-6 TARGET=base
    - PLATFORM=centos-6 TARGET=platform
    - PLATFORM=centos-6 TARGET=couch
    - PLATFORM=centos-7 TARGET=base
    - PLATFORM=centos-7 TARGET=platform
    - PLATFORM=centos-7 TARGET=couch

before_install:
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - ERLANGVERSION=${ERLANGVERSION:-19.3.6} ./build.sh ${TARGET} ${PLATFORM}
