dist: xenial

language: minimal

services:
  - docker

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

env:
  matrix:
    - PLATFORM=debian-jessie TARGET=base
    - PLATFORM=debian-jessie TARGET=platform
    - PLATFORM=debian-jessie TARGET=couch
    - PLATFORM=debian-stretch TARGET=base
    - PLATFORM=debian-stretch TARGET=platform
    - PLATFORM=debian-stretch TARGET=couch
    - PLATFORM=ubuntu-trusty TARGET=base
    - PLATFORM=ubuntu-trusty TARGET=platform
    - PLATFORM=ubuntu-trusty TARGET=couch
    - PLATFORM=ubuntu-xenial TARGET=base
    - PLATFORM=ubuntu-xenial TARGET=platform
    - PLATFORM=ubuntu-xenial TARGET=couch
    - PLATFORM=ubuntu-bionic TARGET=base
    - PLATFORM=ubuntu-bionic TARGET=platform
    - PLATFORM=ubuntu-bionic TARGET=couch
    - PLATFORM=centos-6 TARGET=base
    - PLATFORM=centos-6 TARGET=platform
    - PLATFORM=centos-6 TARGET=couch
    - PLATFORM=centos-7 TARGET=base
    - PLATFORM=centos-7 TARGET=platform
    - PLATFORM=centos-7 TARGET=couch

before_install:
  - docker --version

script:
  - ./build.sh ${TARGET} ${PLATFORM}
