sudo: required

services:
  - docker

env:
  matrix:
    - OS=centos-6
    - OS=centos-7
    - OS=debian-8
    - OS=debian-9
    - OS=ubuntu-14.04
    - OS=ubuntu-16.04

before_script:
  - docker --version

script:
  - find bin/${OS}-base -type d | xargs -I abc abc/create-container.sh
  - find bin/${OS}-erlang* -type d | xargs -I abc abc/create-container.sh

