#!/bin/bash

# These are the images that are currently being used. Make sure we pull them to
# prefill the local docker images so CI runs a bit quicker. The buildkit image
# is from docker buildx so that the worker nodes can be used as part of docker
# buildx multiarch setup. It should match what `docker buildx inspect multiarch
# --bootstrap` pulls.

PULL_IMAGES=(
apache/couchdbci-debian:bookworm-erlang:29.0.2
apache/couchdbci-debian:bookworm-erlang:28.5.0.2
apache/couchdbci-debian:bookworm-erlang-27.3.4.13
apache/couchdbci-debian:bullseye-erlang:27.3.4.13
apache/couchdbci-debian:trixie-erlang:27.3.4.13
apache/couchdbci-ubuntu:resolute-erlang-27.3.4.13
apache/couchdbci-ubuntu:noble-erlang-27.3.4.13
apache/couchdbci-ubuntu:jammy-erlang-27.3.4.13
apache/couchdbci-centos:10-erlang-27.3.4.13
apache/couchdbci-centos:9-erlang-27.3.4.13
apache/couchdbci-centos:8-erlang-27.3.4.13
moby/buildkit:buildx-stable-1
)

docker system prune -af --filter "until=720h"
for image in ${PULL_IMAGES[*]}
do
    echo docker pull ${image}
    docker pull ${image}
done
