#!/bin/bash

DOCKER_ORG="apache"

# These are the images that are currently being used, so don't `docker rmi` them on cleanup.

PULL_IMAGES=(
couchdbci-debian:bookworm-erlang:28.3.2
couchdbci-debian:bookworm-erlang:27.3.4.8
couchdbci-debian:bookworm-erlang-26.2.5.17
couchdbci-debian:bullseye-erlang:26.2.5.17
couchdbci-debian:trixie-erlang:26.2.5.17
couchdbci-ubuntu:noble-erlang-26.2.5.17
couchdbci-ubuntu:jammy-erlang-26.2.5.17
couchdbci-centos:10-erlang-26.2.5.17
couchdbci-centos:9-erlang-26.2.5.17
couchdbci-centos:8-erlang-26.2.5.17
)

# The buildkit one is from docker buildx so that the vm can be used as
# architecture-specific builders. We don't pull this one it's added as
# part of multiarch --bootstrap via ssh

KEEP_IMAGES=(
  "${PULL_IMAGES[@]}"
  buildkit:buildx-stable-1
)

for image in ${PULL_IMAGES[*]}
do
    echo docker pull ${DOCKER_ORG}/${image}
    docker pull ${DOCKER_ORG}/${image}
    # We don't want to delete the current working set of images.
    if ! printf '%s\n' "${KEEP_IMAGES[@]}" | grep -q -P "^${image}$"; then
        echo docker rmi ${DOCKER_ORG}/$image
        docker rmi ${DOCKER_ORG}/$image
    fi
done

docker system prune -f
