# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.

- name: import the Erlang Solutions key into apt
  apt_key:
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present
    # validate_certs: no

- name: add Erlang Solutions deb repository
  apt_repository:
    repo: 'deb http://packages.erlang-solutions.com/ubuntu trusty contrib'
    state: present

# apt-get update
- name: update apt cache
  apt:
    update_cache: yes

- name: install auxiliary packages
  apt: name={{item}} state=present
  with_items:
  - apt-transport-https
  - curl
  - git
  - pkg-config
  - python

# required for make couch
- name: install packages required to build CouchDB
  apt: name={{item}} state=present install_recommends=no
  with_items:
  - build-essential
  - ca-certificates
  - erlang-dev=1:18.2
  - erlang-nox=1:18.2
  - erlang=1:18.2
  - libcurl4-openssl-dev
  - libicu-dev
  - libmozjs185-dev

# required for make docs
- name: install packages required to build CouchDB
  apt: name={{item}} state=present install_recommends=no
  with_items:
  - help2man
  - python-sphinx
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-fonts-recommended
  - texinfo

# More packages found in klaemo's Dockerfile... not sure if required, apparently not?
# - erlang-base-hipe
# - erlang-dialyzer
# - erlang-eunit
# - erlang-manpages
# - libnspr4
# - libnspr4-0d
# - libnspr4-dev
# - openssl
