erlang_solutions_pkg_list:
  - erlang-dev
  - erlang-nox
  - erlang-base
  - erlang-asn1
  - erlang-corba
  - erlang-crypto
  - erlang-diameter
  - erlang-edoc
  - erlang-eldap
  - erlang-erl-docgen
  - erlang-eunit
  - erlang-ic
  - erlang-inets
  - erlang-inviso
  - erlang-mnesia
  - erlang-odbc
  - erlang-os-mon
  - erlang-parsetools
  - erlang-percept
  - erlang-public-key
  - erlang-runtime-tools
  - erlang-snmp
  - erlang-ssh
  - erlang-ssl
  - erlang-syntax-tools
  - erlang-tools
  - erlang-webtool
  - erlang-xmerl
  - erlang-eunit
  - erlang-dialyzer
  - erlang-reltool
  - erlang-wx
