---
- name: create jenkins group
  group:
    name: jenkins
    gid: 112 # same gid as jenkins group on master
    state: present
    system: yes

- name: create jenkins user
  user:
    name: jenkins
    uid: 106 # same uid as jenkins user on master
    state: present
    system: yes
    group: jenkins
    home: "/var/lib/jenkins"

- name: add public key
  authorized_key:
    user: jenkins
    key: "{{ lookup('file', 'keys/couchdb-ci-rsa.pub') }}"
    manage_dir: yes
