name: Image Builder

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Dockerfile'
        required: true
        default: 'debian-bullseye'
      erlangVersion:
        description: 'Erlang/OTP Version'
        required: true
        default: '24.2'
      elixirVersion:
        description: 'Elixir Version'
        required: true
        default: 'v1.12.3'
      platforms:
        description: 'Target Platforms'
        required: true
        default: 'linux/amd64'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/${{ github.event.inputs.dockerfile }}

          push: true

          platforms: ${{ github.event.inputs.platforms }}

          build-args: |
            erlangversion=${{ github.event.inputs.erlangVersion }}
            elixirversion=${{ github.event.inputs.elixirVersion }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.dockerfile }}-${{ github.event.inputs.erlangVersion }}
